"""add_seniority_date_to_dealers

Revision ID: 3f2326ee95bb
Revises: 58e9648aa6fc
Create Date: 2026-03-31 17:36:04.148400
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '3f2326ee95bb'
down_revision: Union[str, None] = '58e9648aa6fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dealers', sa.Column('seniority_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dealers', 'seniority_date')
    # ### end Alembic commands ###
