"""add_ee_number_to_dealers

Revision ID: 86d2fa9131b9
Revises: 8a1e89d10638
Create Date: 2026-04-01 02:13:26.684936
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '86d2fa9131b9'
down_revision: Union[str, None] = '8a1e89d10638'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dealers', sa.Column('ee_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dealers', 'ee_number')
    # ### end Alembic commands ###
