"""remove_foreign_keys_from_request_tables

Revision ID: 8a1e89d10638
Revises: 3f2326ee95bb
Create Date: 2026-03-31 19:01:01.144089
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '8a1e89d10638'
down_revision: Union[str, None] = '3f2326ee95bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('availability_requests_dealer_id_fkey'), 'availability_requests', type_='foreignkey')
    op.drop_constraint(op.f('ride_share_requests_dealer_id_fkey'), 'ride_share_requests', type_='foreignkey')
    op.drop_constraint(op.f('time_off_requests_dealer_id_fkey'), 'time_off_requests', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('time_off_requests_dealer_id_fkey'), 'time_off_requests', 'dealers', ['dealer_id'], ['id'])
    op.create_foreign_key(op.f('ride_share_requests_dealer_id_fkey'), 'ride_share_requests', 'dealers', ['dealer_id'], ['id'])
    op.create_foreign_key(op.f('availability_requests_dealer_id_fkey'), 'availability_requests', 'dealers', ['dealer_id'], ['id'])
    # ### end Alembic commands ###
